# Numpy Vectorized Operations and Broadcasting #



## Traditional Processing ##

Most Python programmers are familiar with the List object, denoted with the `[` and `]` operators. Lists can be used like a dynamic array that grows and shrinks at runtime. They can be accessed by index number and are the basis of many data structures.

In [1]:
data = [ 1, 3, 5, 7, 9 ]
for i in range(len(data)):
    data[i] = data[i] * 2
print(data)

[2, 6, 10, 14, 18]


## Numpy Arrays ##

At the root of Numpy is the `ndarray` object, which stands for n-dimensional array. You can create an `ndarray` from scratch, but the constructor is somewhat complicated. It's easier to create them from the simpler `np.array` object.

In [4]:
%pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 3.4 MB/s eta 0:00:04
   ------ --------------------------------- 2.1/12.6 MB 5.9 MB/s eta 0:00:02
   ---------- ----------------------------- 3.4/12.6 MB 6.1 MB/s eta 0:00:02
   --------------- ------------------------ 5.0/12.6 MB 6.6 MB/s eta 0:00:02
   ------------------- -------------------- 6.3/12.6 MB 6.5 MB/s eta 0:00:01
   ----------------------- ---------------- 7.3/12.6 MB 6.5 MB/s eta 0:00:01
   --------------------------- ------------ 8.7/12.6 MB 6.3 MB/s eta 0:00:01
   ------------------------------ --------- 9.7/12.6 MB 6.2 MB/s eta 0:00:01
   ---------------------------------- ----- 11.0/12.6 MB 6.3 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 6.4 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 6.3 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

data = np.array([ 1, 3, 5, 7, 9])
for i in range(len(data)):
    data[i] = data[i] * 2
print(data)

[ 2  6 10 14 18]


## Numpy Arrays vs Python Lists ##

Python programmers may not be as comfortable with Numpy Arrays. Numpy arrays work similar to Lists but they are faster, more powerful, and a little more difficult to program. Numpy Arrays are a very common data structure for machine learning. 

In [6]:
data = [ 1, 3, 5, 7, 9 ]
data = data * 2
print(data)

[1, 3, 5, 7, 9, 1, 3, 5, 7, 9]


In [7]:
data = np.array([ 1, 3, 5, 7, 9])
data = data * 2
print(data)

[ 2  6 10 14 18]


## Numpy Vectorized Operations ##

Vectorized Operations are a special feature in Numpy module that allow you to perform math operations on every element in an array without using loops. They are much faster than traditional Python loops because Numpy was written in C/C++ and compiled. This means that only one line of Python code must be interpreted "on the fly" and then each of the individual operations execute immediately in machine code. Additionally, the memory structure of the Numpy array is optimized for such operations.

Those of you who have used the Pandas library are familiar with vectorized operations because we use them often on DataFrames. This is because Pandas is built on top of Numpy as uses Numpy arrays to implement DataFrame objects.

In [8]:
data1 = np.array([ 1, 3, 5 ])
data2 = np.array([ 0, 2, 4 ])
data = data1 * data2
print(data)

[ 0  6 20]


## Numpy Operations Along an Axis ##

Be careful mixing Numpy arrays and traditional math operations. The operation will often succeed, but may not be performing the operation that you want and is far less flexible. Use the Numpy equivalent of these functions and then specify the `axis=` parameter to change which dimension of the array is used (e.g., `sum` vs `np.sum`, `max` vs `np.max`, etc.)

In [9]:
# Traditional operator
data = np.array([ [ 1, 3, 5 ], [ 0, 2, 4 ] ])
data = sum(data)
print(data)

[1 5 9]


In [10]:
# Numpy version
data = np.array([ [ 1, 3, 5 ], [ 0, 2, 4 ] ])
data = np.sum(data)
print(data)

15


In [11]:
# Numpy operation based on the first axis (index 0) which is the innermost axis and in this example, a 1-dimensional 3-element array 
data = np.array([ [ 1, 3, 5 ], [ 0, 2, 4 ] ])
data = np.sum(data, axis=0)
print(data)

[1 5 9]


In [12]:
# Numpy operation based on the second axis (index 1) which is the outer axis and in this example, a 1-dimensional 2-element array
data = np.array([ [ 1, 3, 5 ], [ 0, 2, 4 ] ])
data = np.sum(data, axis=1)
print(data)

[9 6]


In [13]:
# Oops, there is no axis at index 2
data = np.array([ [ 1, 3, 5 ], [ 0, 2, 4 ] ])
data = np.sum(data, axis=2)
print(data)

AxisError: axis 2 is out of bounds for array of dimension 2

## Working in 3+ Dimensions ##

Sometimes you will be working with Numpy arrays that are 3 or more dimensions. For example, images are often represented as 3D arrays and a video can be stored as a 4D array. Try to guess the result of each operation and then run the code to confirm your ideas.

In [14]:
# Pretend this is a small 2x2 image with pixels that are red, green, blue, and white.
image = np.array([ [ [ 255, 0, 0 ], [ 0, 255, 0 ] ], [ [0, 0, 255], [255, 255, 255]]])
print(image)

# We want to find the total intensity of each pixel, which means we must take the sum.

[[[255   0   0]
  [  0 255   0]]

 [[  0   0 255]
  [255 255 255]]]


In [15]:
# What do you think the following line of code will produce?
np.sum(image)

np.int64(1530)

In [16]:
# What do you think the following line of code will produce?
np.sum(image, axis=0)

array([[255,   0, 255],
       [255, 510, 255]])

In [17]:
# What do you think the following line of code will produce?
np.sum(image, axis=1)

array([[255, 255,   0],
       [255, 255, 510]])

In [18]:
# What do you think the following line of code will produce?
np.sum(image, axis=2)

array([[255, 255],
       [255, 765]])

## Most Machine Learning Problems use 2D Numpy Arrays ##

Thankfully, most Machine Learning (ML) problems use 2D arrays. Each row is considered a single ***sample*** of training data and the columns represent the ***features*** of each sample. If you are working with ***labeled*** data then it means that you know the correct 'answer' for each sample. For example, if we had ML data representing the length of the hypotenuse in a triangle $c = \sqrt{a^2 + b^2}$, it might look like the following (but remember if you were trying to use ML to solve the hypotenuse length then you wouldn't have the math equation for the Pythagorean Theorem). Note: I have given names to each of the columns here, although most ML algorithms work just fine without the header row that shows the names. 

| Index | Side A | Side B | Side C |
|-------|--------|--------|--------|
| 0     | 3      | 4      | 5      |
| 1     | 5      | 12     | 13     |
| 2     | 7      | 24     | 25     |
| 3     | 8      | 15     | 17     |
| 4     | 9      | 40     | 41     |

Many times we need to separate the labels from the features. We call the labels $y$ and the features $X$. The lowercase $y$ indicates that it is a 1D data whereas the uppercase $X$ means that it is multidimensional.

In [19]:
import numpy as np

# Although the table above has an index column, this is usually implied using the natural indexing that the array provides.
triangle_data = np.array([
    [3, 4, 5],
    [5, 12, 13],
    [7, 24, 25],
    [8, 15, 17],
    [9, 40, 41]
])
print(triangle_data)

[[ 3  4  5]
 [ 5 12 13]
 [ 7 24 25]
 [ 8 15 17]
 [ 9 40 41]]


In [28]:
X = triangle_data[:,0:2]
print(X)
y = triangle_data[:,-1]
print(y)

[[ 3  4]
 [ 5 12]
 [ 7 24]
 [ 8 15]
 [ 9 40]]
[ 5 13 25 17 41]


## Fancy Ways of Creating Numpy Arrays ##

Thus far, the examples have used hardcoded Python lists to initialize each of the Numpy arrays. This works fine for small examples, but for realistic ML problems, all of the data will come from a CSV file or will be downloaded from the internet. For now we will just worry about CSV files. CSV files can be read directly with Numpy or Pandas. Either option is reasonable because most ML libraries can extract the underlying Numpy array from the Pandas DataFrame.

**Note**: Make sure that the file data.csv is in your working directory so that the Jupyter Notebook knows where to find it. If not, you'll need to specify an absolute path. 

In [30]:
%pip install pandas

  Using cached pandas-2.2.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
  Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached pandas-2.2.3-cp312-cp312-win_amd64.whl (11.5 MB)
Using cached pytz-2024.2-py2.py3-none-any.whl (508 kB)
Using cached tzdata-2024.2-py2.py3-none-any.whl (346 kB)
Note: you may need to restart the kernel to use updated packages.


In [31]:
import pandas as pd
df = pd.read_csv('data.csv')
df

Side A  Side B  Side C
0       3       4       5
1       5      12      13
2       7      24      25
3       8      15      17
4       9      40      41

In [32]:
X = df[['Side A', 'Side B']]
y = df['Side C']
print(X)
print(y)

   Side A  Side B
0       3       4
1       5      12
2       7      24
3       8      15
4       9      40
0     5
1    13
2    25
3    17
4    41
Name: Side C, dtype: int64


In [33]:
import numpy as np

data = np.genfromtxt('data.csv', delimiter=',', skip_header=1)
print(data)

[[ 3.  4.  5.]
 [ 5. 12. 13.]
 [ 7. 24. 25.]
 [ 8. 15. 17.]
 [ 9. 40. 41.]]


In [34]:
X = triangle_data[:,0:2]
print(X)
y = triangle_data[:,-1]
print(y)

[[ 3  4]
 [ 5 12]
 [ 7 24]
 [ 8 15]
 [ 9 40]]
[ 5 13 25 17 41]


## Creating 'Dummy' Arrays ##

Many ML computations require you to generate an array of the same size as your data. There are several ways of doing this depending on what you need the initial array values to be.

In [35]:
import numpy as np

arr = np.ones((5, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [37]:
arr = np.zeros((2, 12))
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [38]:
a = np.full((4, 3), 42)
print(a)

[[42 42 42]
 [42 42 42]
 [42 42 42]
 [42 42 42]]


In [39]:
a = np.array([ np.arange(0, 5, 0.5), np.arange(5, 0, -0.5) ])
print(a)

[[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
 [5.  4.5 4.  3.5 3.  2.5 2.  1.5 1.  0.5]]


In [40]:
a = a.flatten()
print(a)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  4.5 4.  3.5 3.  2.5 2.  1.5
 1.  0.5]


In [41]:
a = a.reshape((2, 10))
print(a)

[[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
 [5.  4.5 4.  3.5 3.  2.5 2.  1.5 1.  0.5]]


In [42]:
b = a.copy()
b[1,-1] = 100
print(a)
print(b)

[[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
 [5.  4.5 4.  3.5 3.  2.5 2.  1.5 1.  0.5]]
[[  0.    0.5   1.    1.5   2.    2.5   3.    3.5   4.    4.5]
 [  5.    4.5   4.    3.5   3.    2.5   2.    1.5   1.  100. ]]


## Broadcasting ##

Numpy Broadcasting is closely related to Vectorized Operations and the two often go hand-in-hand. Broadcasting allows you to take two arrays of different dimensions and perform a mathematical operation that requires them to be the same size. Broadcasting is applied automatically and occurs "under the hood" without the programmer having to explicitely specify it. You've already used broadcasting in this notebook without realizing it.  

In [44]:
# Broadcasting extends the integer 2 into a 5 element array [2, 2, 2, 2, 2] and then vectorized operations perform the element-wise multiplication 
data = np.array([ 1, 3, 5, 7, 9])
data = data * 2
print(data)

[ 2  6 10 14 18]


Broadcasting is pretty simple when 1D arrays and scalars are being used, but it can become complicated quickly when working with two multidementional arrays.

In [45]:
# Calculate the Euclidean Distance between two points (e.g., it's basically the Pythagorean Theorem)
#   Each array is a single point 
#   So (0,0) to (3,4) is a distance of 5: remember 3,4,5 triangles from geometry
p1 = np.array([0, 0])
p2 = np.array([3, 4])
print(np.sqrt(np.sum((p1 - p2)**2)))

5.0


In [76]:
# One array is a single point but the other is an array of multiple points...
#   ...and the answer is probably not what we intended
p1 = np.array([0, 0])
p2 = np.array([[3, 4], [6, 8], [9, 12]])
print(p1)
print(p2)
print(np.sqrt(np.sum((p1 - p2)**2)))

[0 0]
[[ 3  4]
 [ 6  8]
 [ 9 12]]
18.708286933869708


In [47]:
#   ...Still probably not what we intended (it's the wrong axis)
p1 = np.array([0, 0])
p2 = np.array([[3, 4], [6, 8], [9, 12]])
print(np.sqrt(np.sum((p1 - p2)**2, axis=0)))

[11.22497216 14.96662955]


In [48]:
#   ...That's the right one!
p1 = np.array([0, 0])
p2 = np.array([[3, 4], [6, 8], [9, 12]])
print(np.sqrt(np.sum((p1 - p2)**2, axis=1)))

[ 5. 10. 15.]


In [49]:
# What if we have two lists of points and we want the distance from each point in one list to each point in the other?
p1 = np.array([[0, 0], [-3, -4,], [-6, -8]])
p2 = np.array([[3, 4], [6, 8], [9, 12]])
print(np.sqrt(np.sum((p1 - p2)**2)))
print(np.sqrt(np.sum((p1 - p2)**2, axis=0)))
print(np.sqrt(np.sum((p1 - p2)**2, axis=1)))

29.58039891549808
[17.74823935 23.66431913]
[ 5. 15. 25.]


In [50]:
# This tells Numpy to create a larger object to fit all of the results
p1 = np.array([[0, 0], [-3, -4,], [-6, -8]])
p2 = np.array([[3, 4], [6, 8], [9, 12]])
print(np.sqrt(np.sum((p1[:, np.newaxis, :] - p2[np.newaxis, :, :]) ** 2, axis=2)))


[[ 5. 10. 15.]
 [10. 15. 20.]
 [15. 20. 25.]]


That last line of code expanded the dimensions of the output array and seemed pretty helpful. But what if we wanted to use the same code for two different situations? In the first situation, we want to calculate the euclidean distance from a single point to an array of points. In the second situation, we want to compare two arrays of points.

In [ ]:
def euclid(p1: list, p2: list) -> list:
    ''' 
    p1: list of numpy points, p2: list of numpy points
    returns: a list of scalar distances between each point 
    '''
    return np.sqrt(np.sum((p1[:, np.newaxis, :] - p2[np.newaxis, :, :]) ** 2, axis=2))

In [106]:
# subtracts a list of points and creates a matrix necessary to fit results

def example_pointlist_subtraction(p1, p2):
  return p1[:, np.newaxis, :] - p2[np.newaxis, :, :]

p1 = np.array([[0,0,0]])
p2 = np.array([[3,3,3]])
print('first example')
print(example_pointlist_subtraction(p1,p2))

p2 = np.array([[0,0,0], [1,1,1]])
p1 = np.array([[3,3,3], [5,5,5]])
print('\nsecond example')
print(example_pointlist_subtraction(p1,p2))

first example
[[[-3 -3 -3]]]

second example
[[[3 3 3]
  [2 2 2]]

 [[5 5 5]
  [4 4 4]]]


In [91]:
# The old code doesn't seem to work
p1 = np.array([0, 0])
p2 = np.array([[3, 4], [6, 8], [9, 12]])
print(euclid(p1, p2)) 

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [92]:
# We can turn the singleton point into an array of points that happens to just have one element in it.
p1 = np.array([[0, 0]])
p2 = np.array([[3, 4], [6, 8], [9, 12]])
print(euclid(p1, p2)) 

[[ 5. 10. 15.]]


In [54]:
# Or even find the distance between two single points
p1 = np.array([[0, 0]])
p2 = np.array([[3, 4]])
print(euclid(p1, p2)) 

[[5.]]


In [192]:
p1 = np.array([[0, 0],[1,1]])
p2 = np.array([[3, 4],[2,2]])
print(euclid(p1, p2)) 

[[5.         2.82842712]
 [3.60555128 1.41421356]]


# Practice, Practice, Practice, and Research #

How did I know about this crazy line of code?

```np.sqrt(np.sum((p1[:, np.newaxis, :] - p2[np.newaxis, :, :]) ** 2, axis=2))```

Lots of practice with simpler code and lots of reading Stackoverflow, the Numpy documentation, and of course some questions to ChatGPT. I don't think any one of these resources on their own would have been enough for me to understand and write the code, but together it all worked together quite nicely. 

In [64]:
# euclidean distance
point1 = np.array([1,2,1])
point2 = np.array([3,3,3])
temp = point1 - point2

sum_sq = np.dot(temp.T, temp) # temp.transpose, temp

# squared distance between two vectors x and y: ||x|| is the (nonnegative) norm/size of the matrix
# ||x-y||^2 = (x-y)(x-y)^T = xx^T - 2xy^T + yy^T

result = np.sqrt(sum_sq)
print(result)

3.0


In [95]:
# manhattan distance 2d
p1 = np.array([0,0,0])
p2 = np.array([3,3,3])

print(p1-p2)

# p = (p_1, p_2, ...) and q = (q_1, q_2, ...)
# for two dimensions: summation of |p_i - q_i|
r = np.sum(np.abs(p1-p2))

print(r)
# result1 = np.abs(np.add(p1, p2))
# print(result1)


[[-3 -3 -3]]
9


In [209]:
# manhattan distance
def manhattan_example(p1: list, p2: list) -> list:
  print('point subtraction')
  print(p1[:, np.newaxis, :] - p2[np.newaxis, :, :])
  print('\nabsolute value')
  print(np.abs(p1[:, np.newaxis, :] - p2[np.newaxis, :, :]))
  print('\nsummation')
  print(np.sum(np.abs(p1[:, np.newaxis, :] - p2[np.newaxis, :, :]), axis=2)) 

In [193]:
def manhattan(p1: list, p2: list) -> list:
  ''' 
  p1: list of numpy points, p2: list of numpy points
  returns: a list of scalar distances between each point using
  '''
  return np.sum(np.abs(p1[:, np.newaxis, :] - p2[np.newaxis, :, :]), axis=2)

In [195]:
p1 = np.array([[0,0,0], [1,1,1]])
p2 = np.array([[2,2,2], [3,3,3]])
# p1 = np.array([[0,0,0]])
# p2 = np.array([[2,2,2], [3,3,3]])
r = manhattan(p1, p2)

print(r)

[[6 9]
 [3 6]]


In [210]:
manhattan_example(p1, p2)

point subtraction
[[[-2 -2 -2]
  [-3 -3 -3]]

 [[-1 -1 -1]
  [-2 -2 -2]]]

absolute value
[[[2 2 2]
  [3 3 3]]

 [[1 1 1]
  [2 2 2]]]

summation
[[6 9]
 [3 6]]


In [233]:
# chebyshev distance
def chebyshev(p1: list, p2: list) -> list:
  return np.max(np.abs(p1[:, np.newaxis, :] - p2[np.newaxis, :, :]), axis=2)

In [231]:
def chebyshev_example(p1: list, p2: list) -> list:
  print('subtraction')
  print(p1[:, np.newaxis, :] - p2[np.newaxis, :, :])
  print('\nabs')
  print(np.abs(p1[:, np.newaxis, :] - p2[np.newaxis, :, :]))
  print('\nmax')
  print(np.max(np.abs(p1[:, np.newaxis, :] - p2[np.newaxis, :, :]), axis=2))

In [242]:
p1 = np.array([[0,1,2], [1,4,9]])
p2 = np.array([[2,2,2], [3,3,3]])
chebyshev(p1, p2)

array([[2, 3],
       [7, 6]])

In [243]:
chebyshev_example(p1,p2)

subtraction
[[[-2 -1  0]
  [-3 -2 -1]]

 [[-1  2  7]
  [-2  1  6]]]

abs
[[[2 1 0]
  [3 2 1]]

 [[1 2 7]
  [2 1 6]]]

max
[[2 3]
 [7 6]]


In [258]:
# cosine distance 2d
p1 = np.array([0,1,2])
p2 = np.array([2,2,2])
def cosine_similarity(p1, p2):
  dotprod = np.dot(p1,p2)
  p1n = np.linalg.norm(p1)
  p2n = np.linalg.norm(p2)

  norm_mult = p1n * p2n
  dot_div_mult = dotprod / norm_mult

  print(dotprod)
  print(p1n)
  print(p2n)
  print(norm_mult)
  print(dot_div_mult)
  return dot_div_mult

print('cosine dist is last one')
print(1-cosine_similarity(p1,p2))


cosine dist is last one
6
2.23606797749979
3.4641016151377544
7.745966692414834
0.7745966692414834
0.2254033307585166


In [332]:
# cosine distance
p1 = np.array([[0,1,2]])
p2 = np.array([[2,2,2], [5,3,1]])
def cosine_distance_example(p1: list, p2: list) -> list:
  print('dot product between points and added together')
  print(np.dot(p1, p2.T))
  print(np.linalg.norm(p1, axis=1))
  print(np.linalg.norm(p2, axis=1))
  print(np.linalg.norm(p1, axis=1) * np.linalg.norm(p2, axis=1))
  print(np.dot(p1, p2.T) / (np.linalg.norm(p1, axis=1) * np.linalg.norm(p2, axis=1)))
  print(1 - (np.dot(p1, p2.T) / (np.linalg.norm(p1, axis=1) * np.linalg.norm(p2, axis=1))))

cosine_distance_example(p1,p2)

dot product between points and added together
[[6 5]]
[2.23606798]
[3.46410162 5.91607978]
[ 7.74596669 13.22875656]
[[0.77459667 0.37796447]]
[[0.22540333 0.62203553]]


In [333]:
def cosine_distance(p1: list, p2: list) -> list:
  return 1 - (np.dot(p1, p2.T) / (np.linalg.norm(p1, axis=1) * np.linalg.norm(p2, axis=1)))

In [334]:
cosine_distance(p1,p2)

array([[0.22540333, 0.62203553]])

In [337]:
# all together

def manhattan(p1: list, p2: list) -> list:
  ''' 
  p1: list of numpy points, p2: list of numpy points
  returns: a list of scalar distances between each point using manhattan
  '''
  return np.sum(np.abs(p1[:, np.newaxis, :] - p2[np.newaxis, :, :]), axis=2)

def chebyshev(p1: list, p2: list) -> list:
  ''' 
  p1: list of numpy points, p2: list of numpy points
  returns: a list of scalar distances between each point using chebyshev
  '''
  return np.max(np.abs(p1[:, np.newaxis, :] - p2[np.newaxis, :, :]), axis=2)

def cosine_distance(p1: list, p2: list) -> list:
  ''' 
  p1: list of numpy points, p2: list of numpy points
  returns: a list of scalar distances between each point using 1 - cosine similarity
  '''
  return 1 - (np.dot(p1, p2.T) / (np.linalg.norm(p1, axis=1) * np.linalg.norm(p2, axis=1)))

print('1st test:')

p1 = np.array([[0,1,2]])
p2 = np.array([[2,2,2]])
print(manhattan(p1, p2))
print(chebyshev(p1, p2))
print(cosine_distance(p1, p2))

print('\n2nd test:')

p1 = np.array([[0,1,2], [1,1,1]])
p2 = np.array([[2,2,2], [3,3,3]])
print(manhattan(p1, p2))
print(chebyshev(p1, p2))
print(cosine_distance(p1, p2))

1st test:
[[3]]
[[2]]
[[0.22540333]]

2nd test:
[[3 6]
 [3 6]]
[[2 3]
 [1 2]]
[[0.22540333 0.        ]
 [0.22540333 0.        ]]
